# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/project_11/project_11.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/project_11/project_11.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib {
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_pkg.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_exception_handler.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_data_registers.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_address_registers.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_opcode_decoder.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_alu.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_bus_interface.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_control.vhd
  /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/68010_vhdl/wf68k10_top.vhd
}
synth_design -top WF68K10_TOP -part xc7z020clg484-1
write_checkpoint -noxdef WF68K10_TOP.dcp
catch { report_utilization -file WF68K10_TOP_utilization_synth.rpt -pb WF68K10_TOP_utilization_synth.pb }
