# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog -library xil_defaultlib -sv /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_top.sv
read_verilog -library xil_defaultlib {
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_noise_lfsr.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_phinc_rom.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_sum_op.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_sh2.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_exptable.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_lfo_lfsr.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_reg.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_sh.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_lin2exp.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_exp2lin.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_sintable.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_pm.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_acc.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_phasegen.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_op.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_timers.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_lfo.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_noise.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_mmr.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51_envelope.v
  /afs/ece.cmu.edu/usr/yiyiz/Private/MM545/YM2151/trunk/jt51_synth/project_1/project_1.srcs/sources_1/imports/jt51_synth/jt51.v
}
synth_design -top jt51_top -part xc7z020clg484-1
write_checkpoint -noxdef jt51_top.dcp
catch { report_utilization -file jt51_top_utilization_synth.rpt -pb jt51_top_utilization_synth.pb }
