# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/ip_repo/edit_top_6116_v1_0.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/ip_repo/edit_top_6116_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/ip_repo/top_6116_1.0 [current_project]
read_verilog -library xil_defaultlib /afs/ece.cmu.edu/usr/cmeredit/Private/class/18545/18545/ip_repo/top_6116_1.0/hdl/top_6116_v1_0_to_bram.v
synth_design -top top_6116_v1_0_to_bram -part xc7z020clg484-1
write_checkpoint -noxdef top_6116_v1_0_to_bram.dcp
catch { report_utilization -file top_6116_v1_0_to_bram_utilization_synth.rpt -pb top_6116_v1_0_to_bram_utilization_synth.pb }
